### ISSUE TITLE
单独运行点淘.js脚本问题

### ISSUE THREAD

**Issue by livvy0918** [walkingsky/autojs_credit#10]
打开点淘之后，一两秒之后自动强制退出是什么原因
![Uploading qq_pic_merged_1704706377402.jpg…]()

**Comment by walkingsky** [comment]
`//设置起始步骤
let start_step = 3;
sleep(5000);

if (start_step <= 1)
    _function.start();

if (start_step <= 2) {

    //签到
    app_taolive.diantao_sign();
}

if (start_step <= 3) {
    //转到元宝中心
    _function.yuanbaozhongxin();
    sleep(2000);
    //走路赚元宝
    app_taolive.duke.zhuanyuanbao();
}`
let start_step = 3; //这里默认是从走路赚元宝开始，默认app已经进了元宝中心页面。没有的话就会认为app没有正常打开，就会重启一遍app再继续执行。
